ALTER TABLE "DailyEntry"
ADD COLUMN IF NOT EXISTS "mealCategory" TEXT NOT NULL DEFAULT 'SNACK';

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "dailyCalorieGoal" INTEGER,
ADD COLUMN IF NOT EXISTS "dailyProteinGoal" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "dailyCarbsGoal" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "dailyFatGoal" DOUBLE PRECISION;
