ALTER TABLE "PantryItem"
RENAME COLUMN "fat" TO "totalFat";

ALTER TABLE "PantryItem"
RENAME COLUMN "carbs" TO "totalCarbohydrate";

ALTER TABLE "PantryItem"
ADD COLUMN "servingsPerContainer" DOUBLE PRECISION,
ADD COLUMN "saturatedFat" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "transFat" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "polyunsaturatedFat" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "monounsaturatedFat" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "cholesterolMg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "sodiumMg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "dietaryFiber" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "totalSugars" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "addedSugars" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "vitaminDMcg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "calciumMg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "ironMg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "potassiumMg" DOUBLE PRECISION NOT NULL DEFAULT 0;
